org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neoforge_version=21.1.222

#mapping_channel=official
#mapping_version=1.21.1

mod_id=relics_thirteenflames
mod_name=Relics: Thirteen Flames

mod_version=0.1.7.7

mod_group_id=com.qurenie.relics_thirteenflames

mod_authors=Storytelling Team

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17